# Generated by Django 4.1.5 on 2023-01-25 01:21

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(default=home.models.generate_bd_phone_number, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
