# Generated by Django 4.1.5 on 2023-01-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_plan_subscription_subscriptioncancellation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_plan', to='home.plan')),
                ('old_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_plan', to='home.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('stripe_charge_id', models.CharField(max_length=255)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.subscription')),
            ],
        ),
    ]
